### ISSUE TITLE
URL 400 Error v1.0.3 

### ISSUE THREAD

**Issue by secondmanveran** [jbrooksuk/laravel-forge-action#22]
No matter which method I try, `trigger_url` or `api` I get the following error using the latest 1.0.3 version.

> curl: (22) The requested URL returned error: 400

When I switch back to 1.0.2 both methods work as expected.

```yaml
deploy:
  name: Deploy to Laravel Forge
  needs: [compile, create, release]
  runs-on: ubuntu-latest

  steps:
    - name: Deploy Production Code
      uses: jbrooksuk/laravel-forge-action@v1.0.3
      with:
        trigger_url: ${{ secrets.MAIN_TRIGGER }}
```

Let me know if there's anything else you need to investigate the issue.
