### ISSUE TITLE
Action Sends Response Before Complete

### ISSUE THREAD

**Issue by secondmanveran** [jbrooksuk/laravel-forge-action#25]
Hey again,

I have a `branch remove` job so that I can use temp branches just for deploying.

The `laravel-forge-action` is sending some sort of complete message before the deployment (on Forge) runs, so that my `remove` job is being triggered and the temp branch is removed and Forge can't find it.

```bash
Wed 01 Feb 2023 09:45:26 AM MST
fatal: couldn't find remote ref latest
```

The two jobs in question look like so:

```yml
deploy:
  name: Deploy to Laravel Forge
  needs: [compile, create, release]
  runs-on: ubuntu-latest

  steps:
    - name: Deploy Production Code
      uses: jbrooksuk/laravel-forge-action@v1.0.4
      with:
        api_key: ${{ secrets.FID }}
        server_id: ${{ secrets.SID }}
        site_id: ${{ secrets.WID }}

remove:
  name: Remove Latest Branch
  needs: [deploy, compile, create, release]
  runs-on: ubuntu-latest

  steps:
    - name: Delete Latest
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.VERAN }}
        branches: latest
```

How can I get this setup so that Forge doesn't send a success response until the deployment has actually started and fetched my `latest` branch?

Thanks
